version: "3.9"

services:
  node-red:
    image: nodered/node-red:1.3.3
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - edgefarm-simulator
    volumes:
      - ./config/node-red:/data

  mosquitto:
    image: eclipse-mosquitto:2.0.10
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - edgefarm-simulator
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  edgefarm-simulator:
