# ===================================================
# meta infos
# ===================================================

meta:
  project: edgefarm-demos
  include:
    - dobi.yaml
    - usecase-1/push-temperature/dobi.yaml
    - usecase-2/monitoring/fleet-seat-info-monitor/dobi.yaml
    - usecase-2/monitoring/train-seat-info-monitor/dobi.yaml
    - usecase-2/passenger-info/seat-info-forwarder/dobi.yaml
    - usecase-2/passenger-info/seat-info-proxy/dobi.yaml
    - usecase-3/vibration_peak_detector/dobi.yaml
    - version.yaml

alias=build:
  tasks:
    - build-and-push-push-temperature
    - build-and-push-fleet-seat-info-monitor
    - build-and-push-train-seat-info-monitor
    - build-and-push-seat-info-forwarder
    - build-and-push-seat-info-proxy
    - build-and-push-vibration-peak-detector

  annotations:
    description: "\t\t\t\t-> [alias] build (and push) all"
    tags:
      - alias
