#
# Variables which differ between the different examples:
#
# docker-context: Relative path in repository where the sources and Dockerfile is located, e.g. GSP-Demo/gps-to-ads-app/src
# docker-image-basename: Name of docker image, without registry. e.g. gps-to-ads-app
#
resource_types:
  - name: docker-buildx
    type: docker-image
    privileged: true
    source:
      repository: starkandwayne/docker-buildx-resource
      tag: edge

resources:
  # Upstream docker images
  - name: image-bb-gitversion-tool
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      tag: 0.8.3

  - name: image-busybox
    type: docker-image
    source:
      repository: busybox
      tag: 1.33.0

  # Git sources
  - name: source
    type: git
    source:
      uri: ((git_source))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))
      paths:
        - ((docker-context))

  # Own docker images
  - name: image-((docker-image-basename))-harbor
    type: docker-buildx
    source:
      repository: harbor.ci4rail.com/edgefarm/((docker-image-basename))
      username: ((harbor_registry_user))
      password: ((harbor_registry_password))

  - name: image-((docker-image-basename))-dockerhub
    type: docker-buildx
    source:
      repository: ci4rail/((docker-image-basename))
      username: ((dockerhub_registry_user))
      password: ((dockerhub_registry_password))

jobs:
  - name: build-((docker-image-basename))
    public: true
    plan:
      - in_parallel:
          - get: image-bb-gitversion-tool
          - get: source
            trigger: true
          - get: image-busybox
      - task: generate-version
        image: image-bb-gitversion-tool
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: gitversion
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                entrypoint.sh &&
                jq empty gitversion/json/gitversion.json &&
                cat gitversion/json/gitversion.json
          params:
            GIT_PATH: source
            GEN_PATH: gitversion
            DEFAULT_BRANCH: ((git_default_branch))
            GIT_BRANCH: ((git_branch))

      - task: generate-build-args-for-images
        image: image-busybox
        config:
          platform: linux
          inputs:
            - name: gitversion
          outputs:
            - name: build-args
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                ROOT=$(pwd)
                echo {\"VERSION\":\"$(cat gitversion/plain/Sha)\"} > build-args/build-args

      - in_parallel:
        - put: image-((docker-image-basename))-harbor
          params:
            build: source/((docker-context))
            buildx_platforms: "linux/amd64,linux/arm64"
            build_args_file: build-args/build-args
            latest: false
            tag_file: gitversion/plain/InformationalVersionDockerLabel

        - put: image-((docker-image-basename))-dockerhub
          params:
            build: source/((docker-context))
            buildx_platforms: "linux/amd64,linux/arm64"
            build_args_file: build-args/build-args
            latest: false
            tag_file: gitversion/plain/InformationalVersionDockerLabel
