version: "3.9"

services:
  node-red:
    image: nodered/node-red:2.2.2
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1881:1880"
    networks:
      - edgefarm-simulator
    volumes:
      - ./config/node-red:/data
    user: "${UID}:${GID}"

  nats:
    image: nats:2.6.5-alpine3.14
    hostname: nats
    expose:
      - 1883
    ports:
      - 1884:1883
    volumes:
      - ./config/nats:/config
      - ../../../creds/:/creds/
    networks:
      - edgefarm-simulator
    command: [ "-js", "-c", "/config/nats.conf" ]

networks:
  edgefarm-simulator:
