---
application: base
modules:
  - name: ads-node-module
    image: harbor.ci4rail.com/edgefarm/ads-node-module:0.1.0-9.Branch.main.Sha.0e4f2e736b64fc1c69b5479743ee89580bdcf3fe
    createOptions: "{}"
    imagePullPolicy: on-create
    restartPolicy: always
    status: running
    startupOrder: 1
  - name: alm-mqtt-module
    image: harbor.ci4rail.com/edgefarm-dev/alm-mqtt-module:7829ba9
    type: edge
    labelSelector:
      mqtt: k8s
    createOptions: "{}"
    imagePullPolicy: on-create
    restartPolicy: always
    status: running
    startupOrder: 1
    envs:
      MQTT_SERVER: <IP1>:1883
  - name: alm-mqtt-module
    image: harbor.ci4rail.com/edgefarm-dev/alm-mqtt-module:7829ba9
    type: edge
    labelSelector:
      mqtt: croco
    createOptions: "{}"
    imagePullPolicy: on-create
    restartPolicy: always
    status: running
    startupOrder: 1
    envs:
      MQTT_SERVER: <IP2>:1883
