---
# Before deploying this manifest, ensure you have deployed the ads-node and alm-mqtt module (see base.yaml)
application: train-simulator
modules:
  - name: edge-demo
    image: harbor.ci4rail.com/edgefarm-dev/train-simulator-edge-demo:d825dc5
    createOptions: "{}"
    imagePullPolicy: on-create
    restartPolicy: always
    status: running
    startupOrder: 1
