# ===================================================
# meta infos
# ===================================================

meta:
  project: train-simulator-edge-demo
  include:
    - dobi.yaml
    - src/dobi.yaml
    - version.yaml

alias=build:
  tasks:
    - build-and-push-demo-image
  annotations:
    description: "\t\t ->[alias] build (and push) all"
    tags:
      - alias
