# ===================================================
# meta infos
# ===================================================

meta:
  project: train-simulator-edge-demo
  include:
    - dobi.yaml
    - version.yaml
