---
# Project configuration
# -----------------------------

# Git configuration
# -----------------
## Specify the git repository to work with
git_source: https://github.com/edgefarm/edgefarm-demos.git
## Specify the git default branch
git_default_branch: main
## Specify the git branch to work with - possible to differ from git_default_branch
git_branch: main
## This enables/disables ssl verification of the git resource
git_skip_ssl_verification: false
