name: usecase-4-pullrequest
on:
  pull_request:
    branches:
      - main
    paths:
      - "demo/usecase-4/**/*"
      - "demo/common/go/**/*"
      - ".github/workflows/usecase-4-pr.yaml"
      - ".github/workflows/usecase-4-main.yaml"

env:
  ARCHITECTURES: linux/arm64,linux/amd64
  DOCKER_REPOSITORY: ci4rail
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-push-dev-receive-position:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into Docker
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ env.ARCHITECTURES }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build
        run: |
          cd demo/usecase-4/;
          docker buildx build \
                      --push \
                      --platform ${ARCHITECTURES} \
                      --build-arg VERSION=${SHORT_SHA::8} \
                      -f build/receive-position/Dockerfile \
                      --tag ${DOCKER_REPOSITORY}/dev-receive-position:latest \
                      --tag ${DOCKER_REPOSITORY}/dev-receive-position:${SHORT_SHA} ../
